In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.model_selection import KFold, cross_val_score, train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score
import xgboost as xgb
import lightgbm as lgb

In [2]:
data=pd.read_csv('C:/Users/HP/Desktop/Data_Sets/ETS2/ETS_Ready_to_ML.csv')

In [3]:
print(data.shape)
data.head()

(720, 24)


Cargo ID  Cargo Weight  Transport Distance  Hour  Minutes  Ferry?  \
0         1            12                2383    33       55       1   
1        35             9                 847    12       56       0   
2        35             9                 317     4       39       0   
3        53            22                1011    14       42       0   
4        53            22                 771    11       23       0   

   Ferry Length  Ferry Cost  Origin City ID  Origin Country  ...  \
0            60         300               0               3  ...   
1             0           0              68              10  ...   
2             0           0              13               6  ...   
3             0           0              90               7  ...   
4             0           0              60               5  ...   

   Transport Type  Trailer Type  High Value Cargo  Heavy Cargo  Fragile Cargo  \
0               1             4                 1            0              0   
1               0             3                 0            0              0   
2               0             3                 0            0              0   
3               0             3                 0            0              0   
4               0             3                 0            0              0   

   ADR Cargo  ADR Class & Type  Special Transport  Price Per KM   Price  
0          0                 0                  0         52.73  126556  
1          0                 0                  0         21.01   18393  
2          0                 0                  0         19.73    6853  
3          0                 0                  0         26.33   27215  
4          0                 0                  0         25.55   20300  

[5 rows x 24 columns]

In [4]:
train=data[['Cargo ID', 'Cargo Weight', 'Transport Distance', 'Hour', 'Minutes',
       'Ferry?', 'Ferry Length', 'Ferry Cost', 'Origin City ID',
       'Origin Country', 'Origin Company', 'Destination City ID',
       'Destination Country', 'Destiantion Company', 'Transport Type',
       'Trailer Type', 'High Value Cargo', 'Heavy Cargo', 'Fragile Cargo',
       'ADR Cargo', 'ADR Class & Type', 'Special Transport']]

In [5]:
test_one=np.array(data['Price Per KM'])
test_one=test_one.reshape(-1,1)
test_two=np.array(data['Price'])
test_two=test_two.reshape(-1,1)

In [7]:
import math

### Gradient Boosting

In [9]:
# Gradient Boosting for Price per km  variable

GBoost=GradientBoostingRegressor(n_estimators=3000, learning_rate=0.05, max_depth=4, max_features='sqrt', min_samples_leaf=15,
                             min_samples_split=10, loss='huber', random_state=5)
GBoost.fit(train,test_one)

# making prediction

GBoost_pred=GBoost.predict(train)
mse=math.sqrt(mean_squared_error(test_one,GBoost_pred))
print('Accuracy score: ',mse)

cross=cross_val_score(GradientBoostingRegressor(),train,test_one,cv=5, scoring='neg_mean_squared_error')
print('Cross Validation score: ', np.mean(cross))

C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy score:  1.8378238173032428


C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of 

Cross Validation score:  -25.85189615190611


In [10]:
# Gradient Boosting for Price variable

GBoost2=GradientBoostingRegressor(n_estimators=3000, learning_rate=0.05, max_depth=4, max_features='sqrt', min_samples_leaf=15,
                             min_samples_split=10, loss='huber', random_state=5)
GBoost2.fit(train,test_two)

# making prediction

GBoost2_pred=GBoost2.predict(train)
mse=math.sqrt(mean_squared_error(test_two,GBoost2_pred))
print('Accuracy score: ',mse)

cross=cross_val_score(GradientBoostingRegressor(),train,test_two,cv=5, scoring='neg_mean_squared_error')
print('Cross Validation score: ', np.mean(cross))

C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy score:  3417.6111478951543


C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of 

Cross Validation score:  -41318861.21079787


In [11]:
GBoost.predict([[1,12,2383,33,55,1,60,300,0,3,19,94,0,20,1,4,1,0,0,0,0,0]])

C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(


array([52.69015223])

In [12]:
GBoost2.predict([[1,12,2383,33,55,1,60,300,0,3,19,94,0,20,1,4,1,0,0,0,0,0]])

C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(


array([95821.83915529])

In [42]:
GBoost.predict([[224,13,135,2,1,0,0,0,94,0,7,8,11,22,1,3,0,0,0,0,0,0]])

C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(


array([27.37882557])

In [43]:
GBoost2.predict([[224,13,135,2,1,0,0,0,94,0,7,8,11,22,1,3,0,0,0,0,0,0]])

C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(


array([4240.81900942])

In [46]:
27.37882557*135

3696.14145195

In [13]:
52.69015223*2383

125560.63276409001

### Exteme Gradient Boosting Regressor

In [35]:
!pip install --upgrade xgboost

  Attempting uninstall: xgboost
    Found existing installation: xgboost 1.5.2
    Uninstalling xgboost-1.5.2:
      Successfully uninstalled xgboost-1.5.2


ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\HP\\NewAnaconda\\anaconda3\\Lib\\site-packages\\~gboost\\lib\\xgboost.dll'
Consider using the `--user` option or check the permissions.



In [26]:
train.shape
train.head()

Cargo ID  Cargo Weight  Transport Distance  Hour  Minutes  Ferry?  \
0         1            12                2383    33       55       1   
1        35             9                 847    12       56       0   
2        35             9                 317     4       39       0   
3        53            22                1011    14       42       0   
4        53            22                 771    11       23       0   

   Ferry Length  Ferry Cost  Origin City ID  Origin Country  ...  \
0            60         300               0               3  ...   
1             0           0              68              10  ...   
2             0           0              13               6  ...   
3             0           0              90               7  ...   
4             0           0              60               5  ...   

   Destination Country  Destiantion Company  Transport Type  Trailer Type  \
0                    0                   20               1             4   
1                    0                   29               0             3   
2                    0                   29               0             3   
3                    0                    4               0             3   
4                    0                    4               0             3   

   High Value Cargo  Heavy Cargo  Fragile Cargo  ADR Cargo  ADR Class & Type  \
0                 1            0              0          0                 0   
1                 0            0              0          0                 0   
2                 0            0              0          0                 0   
3                 0            0              0          0                 0   
4                 0            0              0          0                 0   

   Special Transport  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  

[5 rows x 22 columns]

In [36]:
from xgboost import XGBRegressor

In [37]:
# Exteme Gradient Boosting for Price per km  variable

xgb_one=XGBRegressor(colsample_bytree=0.4603, gamma=0.0468, learning_rate=0.05, max_depth=3, min_child_weight=1.7817,
                          n_estimators=2200, reg_alpha=0.4640, reg_lambda= 0.8571, subsample= 0.5213, silent=1, 
                          random_state=7, nthread=-1)
xgb_one.fit(train,test_one)

# making prediction

xgb_pred=xgb_one.predict(train)
mse=math.sqrt(mean_squared_error(test_one,xgb_pred))
print('Accuracy score: ',mse)

cross=cross_val_score(GradientBoostingRegressor(),train,test_one,cv=5, scoring='neg_mean_squared_error')
print('Cross Validation score: ', np.mean(cross))

[16:43:45] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:576: 
Parameters: { "silent" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


Accuracy score:  0.5999280770470159


C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of 

Cross Validation score:  -25.691156625819247


In [38]:
# Exteme Gradient Boosting for Price  variable

xgb2=XGBRegressor(colsample_bytree=0.4603, gamma=0.0468, learning_rate=0.05, max_depth=3, min_child_weight=1.7817,
                          n_estimators=2200, reg_alpha=0.4640, reg_lambda= 0.8571, subsample= 0.5213, silent=1, 
                          random_state=7, nthread=-1)
xgb2.fit(train,test_two)

# making prediction

xgb2_pred=xgb2.predict(train)
mse=math.sqrt(mean_squared_error(test_two,xgb2_pred))
print('Accuracy score: ',mse)

cross=cross_val_score(GradientBoostingRegressor(),train,test_two,cv=5, scoring='neg_mean_squared_error')
print('Cross Validation score: ', np.mean(cross))

[16:43:59] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:576: 
Parameters: { "silent" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


Accuracy score:  524.7515741554909


C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of 

Cross Validation score:  -41415313.31490405


In [39]:
xgb_one.predict([[1,12,2383,33,55,1,60,300,0,3,19,94,0,20,1,4,1,0,0,0,0,0]])

ValueError: training data did not have the following fields: Cargo ID, Cargo Weight, Transport Distance, Hour, Minutes, Ferry?, Ferry Length, Ferry Cost, Origin City ID, Origin Country, Origin Company, Destination City ID, Destination Country, Destiantion Company, Transport Type, Trailer Type, High Value Cargo, Heavy Cargo, Fragile Cargo, ADR Cargo, ADR Class & Type, Special Transport

### Light Gradient Boosting Regressor

In [30]:
# Light Gradient Boosting for Price per km  variable

lgb_one=lgb.LGBMRegressor(objective='Regression', num_leaves=5, learning_rate=0.05, n_estimators=720, max_bin=55,
                           bagging_fraction=0.8, bagging_freq=5, feature_fraction=0.2319, feature_fraction_seed=9, 
                           bagging_seed=9, min_data_in_leaf=6, min_sum_hessian_in_leaf=11)
lgb_one.fit(train,test_one)

# making prediction

lgb_pred=lgb_one.predict(train)
mse=math.sqrt(mean_squared_error(test_one,lgb_pred))
print('Accuracy score: ',mse)

cross=cross_val_score(GradientBoostingRegressor(),train,test_one,cv=5, scoring='neg_mean_squared_error')
print('Cross Validation score: ', np.mean(cross))

[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5


C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\lightgbm\basic.py:179: UserWarning: Converting column-vector to 1d array
  _log_warning('Converting column-vector to 1d array')


Accuracy score:  3.008337100899479


C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of 

Cross Validation score:  -25.80175449819614


In [31]:
# Light Gradient Boosting for Price   variable

lgb2=lgb.LGBMRegressor(objective='Regression', num_leaves=5, learning_rate=0.05, n_estimators=720, max_bin=55,
                           bagging_fraction=0.8, bagging_freq=5, feature_fraction=0.2319, feature_fraction_seed=9, 
                           bagging_seed=9, min_data_in_leaf=6, min_sum_hessian_in_leaf=11)
lgb2.fit(train,test_two)

# making prediction

lgb2_pred=lgb2.predict(train)
mse=math.sqrt(mean_squared_error(test_two,lgb2_pred))
print('Accuracy score: ',mse)

cross=cross_val_score(GradientBoostingRegressor(),train,test_two,cv=5, scoring='neg_mean_squared_error')
print('Cross Validation score: ', np.mean(cross))

[LightGBM] [Warning] feature_fraction is set=0.2319, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.2319
[LightGBM] [Warning] min_data_in_leaf is set=6, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=6
[LightGBM] [Warning] min_sum_hessian_in_leaf is set=11, min_child_weight=0.001 will be ignored. Current value: min_sum_hessian_in_leaf=11
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5


C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\lightgbm\basic.py:179: UserWarning: Converting column-vector to 1d array
  _log_warning('Converting column-vector to 1d array')


Accuracy score:  3392.3668051447175


C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of 

Cross Validation score:  -40668943.65168665


In [32]:
lgb_one.predict([[1,12,2383,33,55,1,60,300,0,3,19,94,0,20,1,4,1,0,0,0,0,0]])

array([47.32252273])

In [33]:
lgb2.predict([[1,12,2383,33,55,1,60,300,0,3,19,94,0,20,1,4,1,0,0,0,0,0]])

array([111827.79412545])

In [40]:
lgb_one.predict([[224,13,135,2,1,0,0,0,94,0,7,8,11,22,1,3,0,0,0,0,0,0]])

array([27.60937411])

In [41]:
lgb2.predict([[224,13,135,2,1,0,0,0,94,0,7,8,11,22,1,3,0,0,0,0,0,0]])

array([4393.07817917])

In [45]:
27.60937411*135

3705.75

In [52]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV, cross_val_score

In [50]:
# RF regressor with GridsearchCV for Price  variable

randomforest=RandomForestRegressor()

param_grid={'bootstrap': [True, False],
 'max_depth': [10],
 'max_features': ['auto', 'sqrt'],
 'min_samples_leaf': [1, 2],
 'min_samples_split': [2, 5,],
 'n_estimators': [5]}

randomforest2_regressor=GridSearchCV(randomforest,param_grid,scoring='neg_mean_squared_error',cv=5)
randomforest2_regressor.fit(train,test_two)
print(randomforest2_regressor.best_params_)
print(randomforest2_regressor.best_score_)

randomforest2_regressor_predict=randomforest2_regressor.predict(train)

mse=math.sqrt(mean_squared_error(test_two,randomforest2_regressor_predict))
print('Accuracy score: ',mse)

C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataCon

C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataCon

C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataCon

{'bootstrap': True, 'max_depth': 10, 'max_features': 'auto', 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 5}
-43088995.49227846
Accuracy score:  3481.6663616919045


C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


In [54]:
cross=cross_val_score(RandomForestRegressor(),train,test_one,cv=3, scoring='neg_mean_squared_error')
print('Cross Validation score: ', np.mean(cross))

C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HP\NewAnaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


Cross Validation score:  -27.837080262652773
