In [ ]:
Abap, hana, MM

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data=pd.read_excel('C:/Users/HP/Desktop/Data_Sets/ETS2/Transport_Data.xlsx')

In [3]:
print(data.shape)
data.head()

(740, 29)


Cargo Name  Cargo ID  Cargo Weight  Transport Distance  Hour  Minutes  \
0   Pressure Tank       NaN            12                2383    33       55   
1   Post Packages       NaN            11                2029    28       49   
2       Forklifts       NaN            11                2139    30       26   
3      Boric Acid       NaN            16                1814    26        1   
4  Precast Stairs       NaN            22                2147    29       28   

  Ferry?  Ferry Length  Ferry Cost Origin City  ...  Transport Type  \
0    Yes            60         300    Aberdeen  ...          Urgent   
1    Yes            60         300    Carlisle  ...     Very Urgent   
2    Yes            60         300    Aberdeen  ...          Normal   
3    Yes            60         300      Vienna  ...     Very Urgent   
4    Yes            60         300     Glasgow  ...     Very Urgent   

    Trailer Type High Value Cargo  Heavy Cargo Fragile Cargo  ADR Cargo  \
0       Flatbeds              Yes           No            No         No   
1  Curtainsiders               No           No            No         No   
2        Low bed              Yes           No            No         No   
3  Curtainsiders               No           No            No         No   
4  Curtainsiders               No           No            No         No   

  ADR Class & Type Special Transport  Price Per KM   Price  
0              Nil                No         52.73  126556  
1              Nil                No         45.61   93437  
2              Nil                No         41.15   88920  
3              Nil                No         47.60   87242  
4              Nil                No         37.89   82253  

[5 rows x 29 columns]

In [4]:
data.columns

Index(['Cargo Name', 'Cargo ID', 'Cargo Weight', 'Transport Distance', 'Hour',
       'Minutes', 'Ferry?', 'Ferry Length', 'Ferry Cost', 'Origin City',
       'Origin City ID', 'Origin Country', 'Origin Company',
       'Origin Company ID', 'Destination City', 'Destination City ID',
       'Destination Country', 'Destiantion Company', 'Destination Company ID',
       'Transport Type', 'Trailer Type', 'High Value Cargo', 'Heavy Cargo',
       'Fragile Cargo', 'ADR Cargo', 'ADR Class & Type', 'Special Transport',
       'Price Per KM', 'Price'],
      dtype='object')

In [5]:
cols=['Cargo Name', 'Cargo ID', 'Cargo Weight', 'Transport Distance', 'Hour',
       'Minutes', 'Ferry?', 'Ferry Length', 'Ferry Cost', 'Origin City',
       'Origin City ID', 'Origin Country', 'Origin Company',
       'Origin Company ID', 'Destination City', 'Destination City ID',
       'Destination Country', 'Destiantion Company', 'Destination Company ID',
       'Transport Type', 'Trailer Type', 'High Value Cargo', 'Heavy Cargo',
       'Fragile Cargo', 'ADR Cargo', 'ADR Class & Type', 'Special Transport',
       'Price Per KM', 'Price']

In [23]:
a='Ferry?' in cols

In [24]:
print(a)

True


In [6]:
for x in cols:
    print(x, ' :')
    y=len(data[x].unique())
    print(y)
    if y<30:
        print(data[x].unique())

Cargo Name  :
224
Cargo ID  :
1
[nan]
Cargo Weight  :
38
Transport Distance  :
525
Hour  :
35
Minutes  :
60
Ferry?  :
2
['Yes' 'No']
Ferry Length  :
6
[ 60   0 370  49 207  30]
Ferry Cost  :
5
[300   0 995 384 960]
Origin City  :
73
Origin City ID  :
1
[nan]
Origin Country  :
13
['England' 'Austria' 'Slovakia' 'Hungary' 'Germany' 'France' 'Switzerland'
 'Italy' 'Poland' 'Czech Republic' 'Luxembourg' 'Netherlands' 'Belgium']
Origin Company  :
36
Origin Company ID  :
1
[nan]
Destination City  :
90
Destination City ID  :
1
[nan]
Destination Country  :
13
['Austria' 'Poland' 'England' 'Italy' 'Germany' 'Switzerland'
 'Netherlands' 'France' 'Belgium' 'Luxembourg' 'Hungary' 'Slovakia'
 'Czech Republic']
Destiantion Company  :
34
Destination Company ID  :
1
[nan]
Transport Type  :
3
['Urgent' 'Very Urgent' 'Normal']
Trailer Type  :
9
['Flatbeds' 'Curtainsiders' 'Low bed' 'Tank' 'Refrigerated'
 'Container Chassis' 'Articulated Trailer' 'Silo' 'Bulk Carriers']
High Value Cargo  :
2
['Yes' 'No']

In [7]:
cargo=list(data['Cargo Name'].unique())

In [8]:
print(len(cargo))
cargo[:5]

224


['Pressure Tank', 'Post Packages', 'Forklifts', 'Boric Acid', 'Precast Stairs']

In [9]:
cargonoblank=[]

In [10]:
for x in cargo:
    val=len(x.split(' '))
    if val==1:
        var1=x.split(' ')[0]
        cargonoblank.append(var1)
    elif val==2:
        var2=(x.split(' ')[0])+(x.split(' ')[1])
        cargonoblank.append(var2)
    elif val==3:
        var3=(x.split(' ')[0])+(x.split(' ')[1])+(x.split(' ')[2])
        cargonoblank.append(var3)
    elif val==4:
        var4=(x.split(' ')[0])+(x.split(' ')[1])+(x.split(' ')[2])+(x.split(' ')[3])
        cargonoblank.append(var4)
    elif val==5:
        var5=(x.split(' ')[0])+(x.split(' ')[1])+(x.split(' ')[2])+(x.split(' ')[3])+(x.split(' ')[4])
        cargonoblank.append(var5)
    elif val==6:
        var6=(x.split(' ')[0])+(x.split(' ')[1])+(x.split(' ')[2])+(x.split(' ')[3])+(x.split(' ')[4])+(x.split(' ')[5])
        cargonoblank.append(var6)

In [11]:
cargonoblank[220:224]

['NItrogen', 'ReinforcingBars', 'WindTurbineTower', 'SheepWool']

In [12]:
print(len(cargo))
print(len(cargonoblank))
cargodict={cargo[i]:cargonoblank[i] for i in range(len(cargo))}

224
224


In [13]:
cargodict

{'Pressure Tank': 'PressureTank',
 'Post Packages': 'PostPackages',
 'Forklifts': 'Forklifts',
 'Boric Acid': 'BoricAcid',
 'Precast Stairs': 'PrecastStairs',
 'Potassium': 'Potassium',
 'Gasoline': 'Gasoline',
 'Peas': 'Peas',
 'Furniture': 'Furniture',
 'Cars': 'Cars',
 'Outdoor Floor Tiles ': 'OutdoorFloorTiles',
 'Shock Absorbers': 'ShockAbsorbers',
 'Logs': 'Logs',
 'Helicopter- 1808TX': 'Helicopter-1808TX',
 'Nitrocellulose': 'Nitrocellulose',
 'Articulated Hauler Volvo A25G': 'ArticulatedHaulerVolvoA25G',
 'Kerosene': 'Kerosene',
 'Cheese': 'Cheese',
 'Steel Cord': 'SteelCord',
 'Radiators': 'Radiators',
 'Concrete Stairs': 'ConcreteStairs',
 'Chicken Meat': 'ChickenMeat',
 'Crawl Tractor': 'CrawlTractor',
 'Nylon Cord': 'NylonCord',
 'Train Undercarriage': 'TrainUndercarriage',
 'Oil': 'Oil',
 'Fuel Tanker': 'FuelTanker',
 'Fireworks': 'Fireworks',
 'Electronics': 'Electronics',
 'Silica': 'Silica',
 'Iron Pipes': 'IronPipes',
 'Oil Fileters': 'OilFileters',
 'Mercury Chloride 

In [14]:
data[data['Cargo Name']=='Pressure Tank']

Cargo Name  Cargo ID  Cargo Weight  Transport Distance  Hour  Minutes  \
0    Pressure Tank       NaN            12                2383    33       55   
25   Pressure Tank       NaN            12                 997    15        1   
79   Pressure Tank       NaN            12                 803    11       59   
164  Pressure Tank       NaN            12                 702    10        2   
199  Pressure Tank       NaN            12                 579     8       41   
297  Pressure Tank       NaN            12                 418     5       39   
373  Pressure Tank       NaN            12                 354     5       31   

    Ferry?  Ferry Length  Ferry Cost Origin City  ...  Transport Type  \
0      Yes            60         300    Aberdeen  ...          Urgent   
25      No             0           0    Salzburg  ...     Very Urgent   
79      No             0           0     Ostarva  ...     Very Urgent   
164     No             0           0      Calais  ...          Normal   
199     No             0           0   Innsbruck  ...          Urgent   
297     No             0           0       Liege  ...     Very Urgent   
373     No             0           0   Innsbruck  ...     Very Urgent   

    Trailer Type High Value Cargo  Heavy Cargo Fragile Cargo  ADR Cargo  \
0       Flatbeds              Yes           No            No         No   
25       Low bed              Yes           No            No         No   
79      Flatbeds              Yes           No            No         No   
164     Flatbeds              Yes           No            No         No   
199      Low bed              Yes           No            No         No   
297     Flatbeds              Yes           No            No         No   
373      Low bed              Yes           No            No         No   

    ADR Class & Type Special Transport  Price Per KM   Price  
0                Nil                No         52.73  126556  
25               Nil                No         53.19   53632  
79               Nil                No         52.03   42330  
164              Nil                No         45.08   32246  
199              Nil                No         49.25   29116  
297              Nil                No         50.87   21863  
373              Nil                No         50.87   18606  

[7 rows x 29 columns]

In [15]:
li=data[data['Cargo Name']=='Pressure Tank']
length=len(list(li['Cargo Name']))
print(length)

7


In [16]:
num=1

In [17]:
for a,b in cargodict.items():
    
    cargodf=data[data['Cargo Name']==a]
    length=len(list(cargodf['Cargo Name']))
    
    list_one=[]
    while length>0:
        list_one.append(num)
        length-=1
    cargodf['Cargo ID']=list_one
    num=num+1
    vars()[b]=cargodf

C:\Users\HP\AppData\Local\Temp/ipykernel_6436/536657525.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cargodf['Cargo ID']=list_one


In [18]:
PressureTank.head()

Cargo Name  Cargo ID  Cargo Weight  Transport Distance  Hour  Minutes  \
0    Pressure Tank         1            12                2383    33       55   
25   Pressure Tank         1            12                 997    15        1   
79   Pressure Tank         1            12                 803    11       59   
164  Pressure Tank         1            12                 702    10        2   
199  Pressure Tank         1            12                 579     8       41   

    Ferry?  Ferry Length  Ferry Cost Origin City  ...  Transport Type  \
0      Yes            60         300    Aberdeen  ...          Urgent   
25      No             0           0    Salzburg  ...     Very Urgent   
79      No             0           0     Ostarva  ...     Very Urgent   
164     No             0           0      Calais  ...          Normal   
199     No             0           0   Innsbruck  ...          Urgent   

    Trailer Type High Value Cargo  Heavy Cargo Fragile Cargo  ADR Cargo  \
0       Flatbeds              Yes           No            No         No   
25       Low bed              Yes           No            No         No   
79      Flatbeds              Yes           No            No         No   
164     Flatbeds              Yes           No            No         No   
199      Low bed              Yes           No            No         No   

    ADR Class & Type Special Transport  Price Per KM   Price  
0                Nil                No         52.73  126556  
25               Nil                No         53.19   53632  
79               Nil                No         52.03   42330  
164              Nil                No         45.08   32246  
199              Nil                No         49.25   29116  

[5 rows x 29 columns]

In [19]:
data.head()

Cargo Name  Cargo ID  Cargo Weight  Transport Distance  Hour  Minutes  \
0   Pressure Tank       NaN            12                2383    33       55   
1   Post Packages       NaN            11                2029    28       49   
2       Forklifts       NaN            11                2139    30       26   
3      Boric Acid       NaN            16                1814    26        1   
4  Precast Stairs       NaN            22                2147    29       28   

  Ferry?  Ferry Length  Ferry Cost Origin City  ...  Transport Type  \
0    Yes            60         300    Aberdeen  ...          Urgent   
1    Yes            60         300    Carlisle  ...     Very Urgent   
2    Yes            60         300    Aberdeen  ...          Normal   
3    Yes            60         300      Vienna  ...     Very Urgent   
4    Yes            60         300     Glasgow  ...     Very Urgent   

    Trailer Type High Value Cargo  Heavy Cargo Fragile Cargo  ADR Cargo  \
0       Flatbeds              Yes           No            No         No   
1  Curtainsiders               No           No            No         No   
2        Low bed              Yes           No            No         No   
3  Curtainsiders               No           No            No         No   
4  Curtainsiders               No           No            No         No   

  ADR Class & Type Special Transport  Price Per KM   Price  
0              Nil                No         52.73  126556  
1              Nil                No         45.61   93437  
2              Nil                No         41.15   88920  
3              Nil                No         47.60   87242  
4              Nil                No         37.89   82253  

[5 rows x 29 columns]

In [21]:
PostPackages.head()

Cargo Name  Cargo ID  Cargo Weight  Transport Distance  Hour  Minutes  \
1    Post Packages         2            11                2029    28       49   
552  Post Packages         2            11                 328     5       16   
715  Post Packages         2            11                 133     2        3   

    Ferry?  Ferry Length  Ferry Cost Origin City  ...  Transport Type  \
1      Yes            60         300    Carlisle  ...     Very Urgent   
552     No             0           0      Kassel  ...          Normal   
715     No             0           0    Salzburg  ...          Normal   

      Trailer Type High Value Cargo  Heavy Cargo Fragile Cargo  ADR Cargo  \
1    Curtainsiders               No           No            No         No   
552  Curtainsiders               No           No            No         No   
715  Curtainsiders               No           No            No         No   

    ADR Class & Type Special Transport  Price Per KM  Price  
1                Nil                No         45.61  93437  
552              Nil                No         33.63  11631  
715              Nil                No         32.54   4928  

[3 rows x 29 columns]

In [64]:
newdata=pd.DataFrame()

In [65]:
for x in cargonoblank:
        newdata=pd.concat([newdata,vars()[x]])

In [24]:
print(newdata.shape)
newdata.head()

(740, 29)


Cargo Name  Cargo ID  Cargo Weight  Transport Distance  Hour  Minutes  \
0    Pressure Tank         1            12                2383    33       55   
25   Pressure Tank         1            12                 997    15        1   
79   Pressure Tank         1            12                 803    11       59   
164  Pressure Tank         1            12                 702    10        2   
199  Pressure Tank         1            12                 579     8       41   

    Ferry?  Ferry Length  Ferry Cost Origin City  ...  Transport Type  \
0      Yes            60         300    Aberdeen  ...          Urgent   
25      No             0           0    Salzburg  ...     Very Urgent   
79      No             0           0     Ostarva  ...     Very Urgent   
164     No             0           0      Calais  ...          Normal   
199     No             0           0   Innsbruck  ...          Urgent   

    Trailer Type High Value Cargo  Heavy Cargo Fragile Cargo  ADR Cargo  \
0       Flatbeds              Yes           No            No         No   
25       Low bed              Yes           No            No         No   
79      Flatbeds              Yes           No            No         No   
164     Flatbeds              Yes           No            No         No   
199      Low bed              Yes           No            No         No   

    ADR Class & Type Special Transport  Price Per KM   Price  
0                Nil                No         52.73  126556  
25               Nil                No         53.19   53632  
79               Nil                No         52.03   42330  
164              Nil                No         45.08   32246  
199              Nil                No         49.25   29116  

[5 rows x 29 columns]

In [25]:
print(len(newdata['Cargo Name'].unique()))
print(len(newdata['Cargo ID'].unique()))

224
224


### Preparing the Cities variables

In [26]:
ocity=list(newdata['Origin City'].unique())

In [27]:
dcity=list(newdata['Destination City'].unique())

In [28]:
print(len(ocity))
ocity[0:5]

73


['Aberdeen', 'Salzburg', 'Ostarva', 'Calais', 'Innsbruck']

In [30]:
print(len(dcity))
dcity[:5]

90


['Vienna', 'Hamburg', 'Hanover', 'Frankfurt', 'Brno']

In [74]:
#dcity.sort()

In [32]:
totalcity=ocity+dcity

In [35]:
print(len(totalcity))
totalcity[:10]

163


['Aberdeen',
 'Aberdeen',
 'Amsterdam',
 'Amsterdam',
 'B.Bystrica',
 'Berlin',
 'Berlin ',
 'Bern',
 'Bern',
 'Bialystok']

In [34]:
totalcity.sort()

In [31]:
90+73

163

In [37]:
uniquecity=list(set(totalcity))

In [39]:
print(len(uniquecity))
uniquecity.sort()
uniquecity

100


['Aberdeen',
 'Amsterdam',
 'B.Bystrica',
 'Berlin',
 'Berlin ',
 'Bern',
 'Bialystok',
 'Birmingham',
 'Bratislava',
 'Bremen',
 'Brimingham',
 'Brno',
 'Brussels',
 'Budapest',
 'Calais',
 'Calasis',
 'Cambridge',
 'Cardiff',
 'Carlisle',
 'Cologne',
 'Debrecen',
 'Dijon',
 'Dortmund',
 'Dover',
 'Dresden',
 'Duisburg',
 'Dusseldorf',
 'Edinburgh',
 'Erfurt',
 'Felixstowe',
 'Frankfurt',
 'Gandnsk',
 'Garz',
 'Gdansk',
 'Geneva',
 'Glasgow',
 'Grimsby',
 'Groningen',
 'Hamburg',
 'Hanover',
 'Innsbruck',
 'Kassel',
 'Katowice',
 'Kiel',
 'Klagenfurt',
 'Kosice',
 'Krakow',
 'Leipzig',
 'Leipzig ',
 'Liege',
 'Lille',
 'Linz',
 'Liverpool',
 'Lodz',
 'London',
 'Lublin',
 'Luxembourg',
 'Lyon',
 'Madeburg',
 'Manchester',
 'Mannheim',
 'Metz',
 'Milan',
 'Munich',
 'Newcastle',
 'Numberg',
 'Nuremberg',
 'Nurmeberg',
 'Olsztyn',
 'Osnabruck',
 'Ostarva',
 'Ostrava',
 'Paris',
 'Paris ',
 'Pecs',
 'Plymouth',
 'Poznan',
 'Prague',
 'Reims',
 'Rostock',
 'Rotterdam',
 'Salzburg',
 'Shef

In [40]:
cities=uniquecity[:98]

In [41]:
print(len(cities))
cities

98


['Aberdeen',
 'Amsterdam',
 'B.Bystrica',
 'Berlin',
 'Berlin ',
 'Bern',
 'Bialystok',
 'Birmingham',
 'Bratislava',
 'Bremen',
 'Brimingham',
 'Brno',
 'Brussels',
 'Budapest',
 'Calais',
 'Calasis',
 'Cambridge',
 'Cardiff',
 'Carlisle',
 'Cologne',
 'Debrecen',
 'Dijon',
 'Dortmund',
 'Dover',
 'Dresden',
 'Duisburg',
 'Dusseldorf',
 'Edinburgh',
 'Erfurt',
 'Felixstowe',
 'Frankfurt',
 'Gandnsk',
 'Garz',
 'Gdansk',
 'Geneva',
 'Glasgow',
 'Grimsby',
 'Groningen',
 'Hamburg',
 'Hanover',
 'Innsbruck',
 'Kassel',
 'Katowice',
 'Kiel',
 'Klagenfurt',
 'Kosice',
 'Krakow',
 'Leipzig',
 'Leipzig ',
 'Liege',
 'Lille',
 'Linz',
 'Liverpool',
 'Lodz',
 'London',
 'Lublin',
 'Luxembourg',
 'Lyon',
 'Madeburg',
 'Manchester',
 'Mannheim',
 'Metz',
 'Milan',
 'Munich',
 'Newcastle',
 'Numberg',
 'Nuremberg',
 'Nurmeberg',
 'Olsztyn',
 'Osnabruck',
 'Ostarva',
 'Ostrava',
 'Paris',
 'Paris ',
 'Pecs',
 'Plymouth',
 'Poznan',
 'Prague',
 'Reims',
 'Rostock',
 'Rotterdam',
 'Salzburg',
 'Shef

In [42]:
cityids=list(np.arange(98))

In [43]:
print(len(cityids))
cityids

98


[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97]

In [44]:
citydict={cities[i]:cityids[i] for i in range(len(cities))}

In [45]:
citydict

{'Aberdeen': 0,
 'Amsterdam': 1,
 'B.Bystrica': 2,
 'Berlin': 3,
 'Berlin ': 4,
 'Bern': 5,
 'Bialystok': 6,
 'Birmingham': 7,
 'Bratislava': 8,
 'Bremen': 9,
 'Brimingham': 10,
 'Brno': 11,
 'Brussels': 12,
 'Budapest': 13,
 'Calais': 14,
 'Calasis': 15,
 'Cambridge': 16,
 'Cardiff': 17,
 'Carlisle': 18,
 'Cologne': 19,
 'Debrecen': 20,
 'Dijon': 21,
 'Dortmund': 22,
 'Dover': 23,
 'Dresden': 24,
 'Duisburg': 25,
 'Dusseldorf': 26,
 'Edinburgh': 27,
 'Erfurt': 28,
 'Felixstowe': 29,
 'Frankfurt': 30,
 'Gandnsk': 31,
 'Garz': 32,
 'Gdansk': 33,
 'Geneva': 34,
 'Glasgow': 35,
 'Grimsby': 36,
 'Groningen': 37,
 'Hamburg': 38,
 'Hanover': 39,
 'Innsbruck': 40,
 'Kassel': 41,
 'Katowice': 42,
 'Kiel': 43,
 'Klagenfurt': 44,
 'Kosice': 45,
 'Krakow': 46,
 'Leipzig': 47,
 'Leipzig ': 48,
 'Liege': 49,
 'Lille': 50,
 'Linz': 51,
 'Liverpool': 52,
 'Lodz': 53,
 'London': 54,
 'Lublin': 55,
 'Luxembourg': 56,
 'Lyon': 57,
 'Madeburg': 58,
 'Manchester': 59,
 'Mannheim': 60,
 'Metz': 61,
 'Milan

In [46]:
newdata.head()

Cargo Name  Cargo ID  Cargo Weight  Transport Distance  Hour  Minutes  \
0    Pressure Tank         1            12                2383    33       55   
25   Pressure Tank         1            12                 997    15        1   
79   Pressure Tank         1            12                 803    11       59   
164  Pressure Tank         1            12                 702    10        2   
199  Pressure Tank         1            12                 579     8       41   

    Ferry?  Ferry Length  Ferry Cost Origin City  ...  Transport Type  \
0      Yes            60         300    Aberdeen  ...          Urgent   
25      No             0           0    Salzburg  ...     Very Urgent   
79      No             0           0     Ostarva  ...     Very Urgent   
164     No             0           0      Calais  ...          Normal   
199     No             0           0   Innsbruck  ...          Urgent   

    Trailer Type High Value Cargo  Heavy Cargo Fragile Cargo  ADR Cargo  \
0       Flatbeds              Yes           No            No         No   
25       Low bed              Yes           No            No         No   
79      Flatbeds              Yes           No            No         No   
164     Flatbeds              Yes           No            No         No   
199      Low bed              Yes           No            No         No   

    ADR Class & Type Special Transport  Price Per KM   Price  
0                Nil                No         52.73  126556  
25               Nil                No         53.19   53632  
79               Nil                No         52.03   42330  
164              Nil                No         45.08   32246  
199              Nil                No         49.25   29116  

[5 rows x 29 columns]

### Updating values for Origin city variable

In [71]:
num=1

In [72]:
for a,b in citydict.items():
    df=newdata[newdata['Origin City']==a]
    length=len(list(df['Origin City']))
    print(length)
    if length==0:
        pass
    else:
        list_one=[]
        while length>0:
            list_one.append(b)
            length-=1
        df['Origin City ID']=list_one
        num=num+1
        vars()[a]=df

13
13
0
11
0
7
10
9
12
9
0
12
0
12
12
0
0
0
6
5
9
0
11
8
0
9
6
0
5
15
11
0
18
9
10
12
8
5
8
15
12
4
0
8
18
14
0
6
0
9
7
14
0
11
12
11
10
14
0
12
5
0
0
9
0
1
7
0
14
8
11
0
0
19
0
10
7
13
10
5
12
18
13
0
13
14
10
6
13
1
0
10
10
7
18


C:\Users\HP\AppData\Local\Temp/ipykernel_6436/3659317956.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Origin City ID']=list_one


8
6
10


In [73]:
Amsterdam['Origin City ID']

603    1
182    1
496    1
59     1
640    1
80     1
427    1
274    1
569    1
263    1
575    1
488    1
639    1
Name: Origin City ID, dtype: int32

In [78]:
newdataone=pd.DataFrame()

In [79]:
for x in ocity:
        newdataone=pd.concat([newdataone,vars()[x]])

In [80]:
print(newdataone.shape)
newdataone.head()

(740, 29)


Cargo Name  Cargo ID  Cargo Weight  Transport Distance  Hour  \
0         Pressure Tank         1            12                2383    33   
2             Forklifts         3            11                2139    30   
148  Helicopter- 1808TX        14             3                 572     8   
289         Fuel Tanker        27             9                 595     8   
328            Tractors        41            11                 395     5   

     Minutes Ferry?  Ferry Length  Ferry Cost Origin City  ...  \
0         55    Yes            60         300    Aberdeen  ...   
2         26    Yes            60         300    Aberdeen  ...   
148        8     No             0           0    Aberdeen  ...   
289       25     No             0           0    Aberdeen  ...   
328       33     No             0           0    Aberdeen  ...   

     Transport Type Trailer Type High Value Cargo  Heavy Cargo Fragile Cargo  \
0            Urgent     Flatbeds              Yes           No            No   
2            Normal      Low bed              Yes           No            No   
148          Normal      Low bed              Yes           No           Yes   
289          Urgent         Tank               No           No            No   
328     Very Urgent      Low bed               No           No            No   

     ADR Cargo            ADR Class & Type Special Transport  Price Per KM  \
0           No                         Nil                No         52.73   
2           No                         Nil                No         41.15   
148         No                         Nil                No         57.12   
289        Yes  Class 3- Flammable Liquids                No         37.18   
328         No                         Nil                No         49.90   

      Price  
0    126556  
2     88920  
148   33274  
289   22723  
328   20309  

[5 rows x 29 columns]

In [134]:
newdataone['Origin City ID'].unique()

array([ 0, 81, 70, 14, 40, 49, 18, 41,  8, 50, 97, 34, 20, 11, 85, 26, 94,
       35, 54, 68, 78, 69, 39, 92, 73,  3, 77,  7, 45, 59,  6, 29, 30, 44,
       43, 63, 82, 56, 93, 95, 88, 75, 96, 65, 51, 22, 76, 13, 84, 55, 19,
       87, 57,  1, 33, 86, 66, 80, 91, 37, 79,  5, 53, 38, 32, 28,  9, 60,
       36, 23, 25, 47, 89])

### Updating the values for Destination city values

In [84]:
newdataone.head()

Cargo Name  Cargo ID  Cargo Weight  Transport Distance  Hour  \
0         Pressure Tank         1            12                2383    33   
2             Forklifts         3            11                2139    30   
148  Helicopter- 1808TX        14             3                 572     8   
289         Fuel Tanker        27             9                 595     8   
328            Tractors        41            11                 395     5   

     Minutes Ferry?  Ferry Length  Ferry Cost Origin City  ...  \
0         55    Yes            60         300    Aberdeen  ...   
2         26    Yes            60         300    Aberdeen  ...   
148        8     No             0           0    Aberdeen  ...   
289       25     No             0           0    Aberdeen  ...   
328       33     No             0           0    Aberdeen  ...   

     Transport Type Trailer Type High Value Cargo  Heavy Cargo Fragile Cargo  \
0            Urgent     Flatbeds              Yes           No            No   
2            Normal      Low bed              Yes           No            No   
148          Normal      Low bed              Yes           No           Yes   
289          Urgent         Tank               No           No            No   
328     Very Urgent      Low bed               No           No            No   

     ADR Cargo            ADR Class & Type Special Transport  Price Per KM  \
0           No                         Nil                No         52.73   
2           No                         Nil                No         41.15   
148         No                         Nil                No         57.12   
289        Yes  Class 3- Flammable Liquids                No         37.18   
328         No                         Nil                No         49.90   

      Price  
0    126556  
2     88920  
148   33274  
289   22723  
328   20309  

[5 rows x 29 columns]

In [85]:
num=1

In [90]:
for a,b in citydict.items():
    df=newdata[newdata['Destination City']==a]
    length=len(list(df['Destination City']))
    print(length)
    if length==0:
        pass
    else:
        list_one=[]
        while length>0:
            list_one.append(b)
            length-=1
        df['Destination City ID']=list_one
        num=num+1
        vars()[a]=df

8
16
14
0
8
6
9
10
2
5
1
12
9
9
0
13
3
2
7
2
8
6
11
8
12
14
9
5
1
11
11
1
23
7
13
2
9
6
11
11
14
4
14
1
0
3
8
0
3
14
12
24
1
13
7
11
14
7
2
5
5
9
9
4
2
0
0
12
5
11
0
7
11
0
5
5
4
9
3
6
20
25
9
6
13
5
4
5
5
3
5
0
3
7
12
10
0
9


C:\Users\HP\AppData\Local\Temp/ipykernel_6436/3665011429.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Destination City ID']=list_one


In [91]:
Aberdeen.head(8)

Cargo Name  Cargo ID  Cargo Weight  Transport Distance  Hour  \
8               Furniture         9            16                1754    25   
13                   Logs        13            22                2266    37   
34                 Silica        30            19                1473    20   
444         Empty Pallets        53            22                 586     7   
305           Large Tubes       100            22                 591     8   
169             Chemicals       112            18                 656     9   
449  Industrial Condenser       119            60                 236     6   
448     Massive Tech Part       156            44                 236     6   

     Minutes Ferry?  Ferry Length  Ferry Cost Origin City  ...  \
8         10    Yes            60         300     Hanover  ...   
13        27    Yes            60         300    Salzburg  ...   
34        56    Yes            60         300     Cologne  ...   
444       56     No             0           0  Manchester  ...   
305       23     No             0           0   Sheffield  ...   
169       23     No             0           0     Grimsby  ...   
449       35     No             0           0     Glasgow  ...   
448       35     No             0           0     Glasgow  ...   

     Transport Type   Trailer Type High Value Cargo  Heavy Cargo  \
8            Normal  Curtainsiders               No           No   
13           Normal       Flatbeds               No           No   
34           Urgent  Curtainsiders               No           No   
444          Normal  Curtainsiders               No           No   
305     Very Urgent       Flatbeds               No           No   
169          Urgent           Tank               No           No   
449          Normal        Low bed              Yes          Yes   
448          Normal        Low bed              Yes          Yes   

    Fragile Cargo  ADR Cargo ADR Class & Type Special Transport  Price Per KM  \
8             Yes         No              Nil                No         40.38   
13             No         No              Nil                No         28.27   
34             No         No              Nil                No         34.42   
444            No         No              Nil                No         25.55   
305            No         No              Nil                No         35.10   
169            No        Yes   Class 2- Gases                No         47.48   
449            No         No              Nil               Yes         63.00   
448            No         No              Nil               Yes         63.00   

     Price  
8    71726  
13   63830  
34   51596  
444  15572  
305  21343  
169  31747  
449  15513  
448  15513  

[8 rows x 29 columns]

In [92]:
Amsterdam['Destination City ID']

733    1
498    1
602    1
146    1
235    1
442    1
374    1
586    1
683    1
197    1
207    1
489    1
286    1
401    1
400    1
728    1
Name: Destination City ID, dtype: int32

In [97]:
newdatatwo=pd.DataFrame()

In [98]:
for x in dcity:
    try:
        newdatatwo=pd.concat([newdatatwo,vars()[x]])
    except KeyError:
        pass

In [99]:
print(newdatatwo.shape)
newdatatwo.head()

(720, 29)


Cargo Name  Cargo ID  Cargo Weight  Transport Distance  Hour  Minutes  \
0    Pressure Tank         1            12                2383    33       55   
379  Used Plastics        35             9                 847    12       56   
687  Used Plastics        35             9                 317     4       39   
220  Empty Pallets        53            22                1011    14       42   
330  Empty Pallets        53            22                 771    11       23   

    Ferry?  Ferry Length  Ferry Cost Origin City  ...  Transport Type  \
0      Yes            60         300    Aberdeen  ...          Urgent   
379     No             0           0     Olsztyn  ...          Normal   
687     No             0           0    Budapest  ...          Normal   
220     No             0           0      Turnin  ...          Normal   
330     No             0           0    Mannheim  ...          Normal   

      Trailer Type High Value Cargo  Heavy Cargo Fragile Cargo  ADR Cargo  \
0         Flatbeds              Yes           No            No         No   
379  Curtainsiders               No           No            No         No   
687  Curtainsiders               No           No            No         No   
220  Curtainsiders               No           No            No         No   
330  Curtainsiders               No           No            No         No   

    ADR Class & Type Special Transport  Price Per KM   Price  
0                Nil                No         52.73  126556  
379              Nil                No         21.01   18393  
687              Nil                No         19.73    6853  
220              Nil                No         26.33   27215  
330              Nil                No         25.55   20300  

[5 rows x 29 columns]

### Preparing Companies variables

In [100]:
ocomp=list(newdatatwo['Origin Company'].unique())

In [101]:
dcomp=list(newdatatwo['Origin Company'].unique())

In [102]:
totalcomp=ocomp+dcomp

In [106]:
print(len(totalcomp))
totalcomp

72


['AI',
 'AI',
 'BCP',
 'BCP',
 'BHV',
 'BHV',
 'Batisse',
 'Batisse',
 'CNP',
 'CNP',
 'Dom Keps',
 'Dom Keps',
 'Euro Acers',
 'Euro Acers',
 'Euro Goodies',
 'Euro Goodies',
 'FCP',
 'FCP',
 'FLE',
 'FLE',
 'Government',
 'Government',
 'IKA',
 'IKA',
 'ITCC',
 'ITCC',
 'ITS',
 'ITS',
 'Kaarfor',
 'Kaarfor',
 'Kathode',
 'Kathode',
 'Kolice',
 'Kolice',
 'LKW',
 'LKW',
 'Lisette Logistics',
 'Lisette Logistics',
 'NBFC',
 'NBFC',
 'NS Oil',
 'NS Oil',
 'Polar Lines',
 'Polar Lines',
 'Posped',
 'Posped',
 'RENAT',
 'RENAT',
 'RTLOG',
 'RTLOG',
 'Sand Builders',
 'Sand Builders',
 'Scout',
 'Scout',
 'Sell Plan',
 'Sell Plan',
 'Stein Brunch',
 'Stein Brunch',
 'Stokes',
 'Stokes',
 'Tradeaux',
 'Tradeaux',
 'Trameri',
 'Trameri',
 'Treeet',
 'Treeet',
 'Voilureuz',
 'Voilureuz',
 'WGCC',
 'WGCC',
 'transinet',
 'transinet']

In [105]:
totalcomp.sort()

In [107]:
uniqcomp=list(set(totalcomp))

In [110]:
print(len(uniqcomp))
uniqcomp

36


['AI',
 'BCP',
 'BHV',
 'Batisse',
 'CNP',
 'Dom Keps',
 'Euro Acers',
 'Euro Goodies',
 'FCP',
 'FLE',
 'Government',
 'IKA',
 'ITCC',
 'ITS',
 'Kaarfor',
 'Kathode',
 'Kolice',
 'LKW',
 'Lisette Logistics',
 'NBFC',
 'NS Oil',
 'Polar Lines',
 'Posped',
 'RENAT',
 'RTLOG',
 'Sand Builders',
 'Scout',
 'Sell Plan',
 'Stein Brunch',
 'Stokes',
 'Tradeaux',
 'Trameri',
 'Treeet',
 'Voilureuz',
 'WGCC',
 'transinet']

In [109]:
uniqcomp.sort()

In [111]:
newdatatwo.columns

Index(['Cargo Name', 'Cargo ID', 'Cargo Weight', 'Transport Distance', 'Hour',
       'Minutes', 'Ferry?', 'Ferry Length', 'Ferry Cost', 'Origin City',
       'Origin City ID', 'Origin Country', 'Origin Company',
       'Origin Company ID', 'Destination City', 'Destination City ID',
       'Destination Country', 'Destiantion Company', 'Destination Company ID',
       'Transport Type', 'Trailer Type', 'High Value Cargo', 'Heavy Cargo',
       'Fragile Cargo', 'ADR Cargo', 'ADR Class & Type', 'Special Transport',
       'Price Per KM', 'Price'],
      dtype='object')

In [112]:
cols=['Cargo Name', 'Cargo ID', 'Cargo Weight', 'Transport Distance', 'Hour',
       'Minutes', 'Ferry?', 'Ferry Length', 'Ferry Cost', 'Origin City',
       'Origin City ID', 'Origin Country', 'Origin Company',
       'Origin Company ID', 'Destination City', 'Destination City ID',
       'Destination Country', 'Destiantion Company', 'Destination Company ID',
       'Transport Type', 'Trailer Type', 'High Value Cargo', 'Heavy Cargo',
       'Fragile Cargo', 'ADR Cargo', 'ADR Class & Type', 'Special Transport',
       'Price Per KM', 'Price']

In [141]:
for x in cols:
    print(x, ' :')
    y=len(newdatatwo[x].unique())
    print(y)
    if y<30:
        print(newdatatwo[x].unique())

Cargo Name  :
223
Cargo ID  :
223
Cargo Weight  :
38
Transport Distance  :
516
Hour  :
35
Minutes  :
60
Ferry?  :
2
[1 2]
Ferry Length  :
6
[ 60   0 370 207  49  30]
Ferry Cost  :
5
[300   0 995 960 384]
Origin City  :
73
Origin City ID  :
2
[nan 97.]
Origin Country  :
13
[ 3 10  6  7  5 11  0 12  4  9  2  1  8]
Origin Company  :
36
Origin Company ID  :
1
[nan]
Destination City  :
88
Destination City ID  :
88
Destination Country  :
13
[ 0  7  5  2  4 10  3  6  9  8 12  1 11]
Destiantion Company  :
34
Destination Company ID  :
1
[nan]
Transport Type  :
3
[1 0 2]
Trailer Type  :
9
[4 3 6 5 8 2 0 7 1]
High Value Cargo  :
2
[1 2]
Heavy Cargo  :
2
[2 1]
Fragile Cargo  :
2
[0 1]
ADR Cargo  :
2
[0 1]
ADR Class & Type  :
7
[0 3 1 5 6 2 4]
Special Transport  :
2
[0 1]
Price Per KM  :
530
Price  :
704


In [121]:
newdatatwo['Ferry?']=newdatatwo['Ferry?'].replace({'Yes':1,'No':0})

In [115]:
newdatatwo['Origin Country']=newdatatwo['Origin Country'].replace({'Austria':0,'Belgium':1,'Czech Republic':2,'England':3,
                                                                  'France':4,'Germany':5,'Hungary':6,'Italy':7,'Luxembourg':8,
                                                                  'Netherlands':9,'Poland':10,'Slovakia':11,'Switzerland':12})

In [117]:
newdatatwo['Destination Country']=newdatatwo['Destination Country'].replace({'Austria':0,'Belgium':1,'Czech Republic':2,'England':3,
                                                                  'France':4,'Germany':5,'Hungary':6,'Italy':7,'Luxembourg':8,
                                                                  'Netherlands':9,'Poland':10,'Slovakia':11,'Switzerland':12})

In [118]:
newdatatwo['Transport Type']=newdatatwo['Transport Type'].replace({'Normal':0,'Urgent':1,'Very Urgent':2})

In [131]:
newdatatwo['Trailer Type']=newdatatwo['Trailer Type'].replace({'Articulated Trailer':0,'Bulk Carriers':1,'Container Chassis':2,
                                                               'Curtainsiders':3,'Flatbeds':4,'Low bed':5,'Refrigerated':6,
                                                                'Silo':7,'Tank':8})

In [124]:
newdatatwo['High Value Cargo']=newdatatwo['High Value Cargo'].replace({'Yes':1,'No':0})

In [125]:
newdatatwo['Heavy Cargo']=newdatatwo['Heavy Cargo'].replace({'Yes':1,'No':0})

In [126]:
newdatatwo['Fragile Cargo']=newdatatwo['Fragile Cargo'].replace({'Yes':1,'No':0})

In [127]:
newdatatwo['ADR Cargo']=newdatatwo['ADR Cargo'].replace({'Yes':1,'No':0})

In [128]:
newdatatwo['ADR Class & Type']=newdatatwo['ADR Class & Type'].replace({'Nil':0,'Class 1- Explosives':1,
                                                                      'Class 2- Gases':2,'Class 3- Flammable Liquids':3,
                                                                      'Class 4- Flammable Solids':4,
                                                                      'Class 6- Toxic & Infectious substances':5,
                                                                      'Class 8- Corrosive substances':6})

In [129]:
newdatatwo['Special Transport']=newdatatwo['Special Transport'].replace({'Yes':1,'No':0})

In [136]:
newdatatwo['Origin Company'].unique()

array(['NBFC', 'Sell Plan', 'Kaarfor', 'Trameri', 'Euro Goodies',
       'Tradeaux', 'LKW', 'Posped', 'Stein Brunch', 'RENAT', 'NS Oil',
       'WGCC', 'transinet', 'ITCC', 'Treeet', 'IKA', 'Government',
       'Stokes', 'Euro Acers', 'Sand Builders', 'RTLOG', 'AI', 'BCP',
       'Lisette Logistics', 'FCP', 'FLE', 'BHV', 'CNP', 'ITS', 'Dom Keps',
       'Scout', 'Polar Lines', 'Kolice', 'Voilureuz', 'Kathode',
       'Batisse'], dtype=object)

In [137]:
newdatatwo['Origin Company']=newdatatwo['Origin Company'].replace({'AI':0,'Batisse':1,'BCP':2,'BHV':3,'CNP':4,'Dom Keps':5,
                                                                  'Euro Acers':6,'Euro Goodies':7,'FCP':8,'FLE':9,
                                                                  'Government':10,'IKA':11,'ITCC':12,'ITS':13,'Kaarfar':14,
                                                                  'Kathode':15,'Kolice':16,'Lisette Logistics':17,'LKW':18,
                                                                  'NBFC':19, 'NS Oil':20,'Polar Lines':21,'Posped':22,
                                                                   'RENAT':23,'RTLOG':24,'Sand Builders':25,'Scout':26,
                                                                  'Sell Plan':27,'Stein Brunch':28,'Stokes':29,'Tradeaux':30,
                                                                  'Trameri':31,'transinet':32,'Treeet':33,'Voilureuz':34,
                                                                   'WGCC':35})

In [138]:
newdatatwo['Destiantion Company']=newdatatwo['Destiantion Company'].replace({'AI':0,'Batisse':1,'BCP':2,'BHV':3,'CNP':4,'Dom Keps':5,
                                                                  'Euro Acers':6,'Euro Goodies':7,'FCP':8,'FLE':9,
                                                                  'Government':10,'IKA':11,'ITCC':12,'ITS':13,'Kaarfar':14,
                                                                  'Kathode':15,'Kolice':16,'Lisette Logistics':17,'LKW':18,
                                                                  'NBFC':19, 'NS Oil':20,'Polar Lines':21,'Posped':22,
                                                                   'RENAT':23,'RTLOG':24,'Sand Builders':25,'Scout':26,
                                                                  'Sell Plan':27,'Stein Brunch':28,'Stokes':29,'Tradeaux':30,
                                                                  'Trameri':31,'transinet':32,'Treeet':33,'Voilureuz':34,
                                                                   'WGCC':35})

## {'ACI':36,'Cargotras':37,'CS':38,'D':39,'H':40,'Spinelli':41}

In [139]:
newdatatwo.head()

Cargo Name  Cargo ID  Cargo Weight  Transport Distance  Hour  Minutes  \
0    Pressure Tank         1            12                2383    33       55   
379  Used Plastics        35             9                 847    12       56   
687  Used Plastics        35             9                 317     4       39   
220  Empty Pallets        53            22                1011    14       42   
330  Empty Pallets        53            22                 771    11       23   

     Ferry?  Ferry Length  Ferry Cost Origin City  ...  Trailer Type  \
0         1            60         300    Aberdeen  ...             4   
379       2             0           0     Olsztyn  ...             3   
687       2             0           0    Budapest  ...             3   
220       2             0           0      Turnin  ...             3   
330       2             0           0    Mannheim  ...             3   

     High Value Cargo Heavy Cargo  Fragile Cargo ADR Cargo  ADR Class & Type  \
0                   1           2              0         0                 0   
379                 2           2              0         0                 0   
687                 2           2              0         0                 0   
220                 2           2              0         0                 0   
330                 2           2              0         0                 0   

     Special Transport Price Per KM   Price  Trailer Type   
0                    0        52.73  126556              4  
379                  0        21.01   18393              3  
687                  0        19.73    6853              3  
220                  0        26.33   27215              3  
330                  0        25.55   20300              3  

[5 rows x 30 columns]

In [142]:
newdatatwo.to_csv('ETS_Ready_to_ML.csv')

In [135]:
newdataone.to_csv('Newdataone.csv')